version: '3.7'
services: 
    server:
        container_name: vls
        build:
            context: ./Backend
            dockerfile: Dockerfile
        image: vls:1.0
        networks:
            - default
        runtime: nvidia
        environment: 
            FLASK_ENV: ${FLASK_ENV}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASS: ${POSTGRES_PASS}
            POSTGRES_SERVER: ${POSTGRES_SERVER}
            POSTGRES_NAME: ${POSTGRES_NAME}
            NVIDIA_VISIBLE_DEVICES: all
            TZ: "Asia/Seoul"
            ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL}
            ADMIN: ${ADMIN}
            PASSWORD: ${PASSWORD}
        volumes:
            - ./Backend/src:/usr/src/Backend/src
            - /hdd_ext2/storage:/home/storage
        ports:
            - 5500:80
        depends_on: 
            - db
        links:
            - db

    db:
        image: postgres:13.4-alpine
        container_name: postgres_vls
        restart: always
        environment: 
            POSTGRES_DB: ${POSTGRES_NAME}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASS}
            TZ: "Asia/Seoul"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
            # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports: 
            - "5433:5432"

    mosquitto:
        image: vimagick/mosquitto
        ports:
            - "1883:1883"
            - "8883:8883"
        volumes:
            - ./data/mosquitto.conf:/etc/mosquitto/mosquitto.conf
            - ./data/pwfile:/etc/mosquitto/pwfile
            - ./data:/var/lib/mosquitto
        restart: always