version: '3.7'
services: 
    server:
        container_name: vls
        build:
            context: ./Backend
            dockerfile: Dockerfile
        image: vls:1.0
        networks:
            - default
        runtime: nvidia
        environment: 
            FLASK_ENV: ${FLASK_ENV}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASS: ${POSTGRES_PASS}
            POSTGRES_SERVER: ${POSTGRES_SERVER}
            POSTGRES_NAME: ${POSTGRES_NAME}
            NVIDIA_VISIBLE_DEVICES: all
            TZ: "Asia/Seoul"
        volumes:
            - ./Backend/src:/usr/src/Backend/src
        ports:
            - 5000:80
        depends_on: 
            - db
        links:
            - db

    db:
        image: postgres
        container_name: postgres_vls
        restart: always
        environment: 
            POSTGRES_DB: ${POSTGRES_NAME}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASS}
            TZ: "Asia/Seoul"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports: 
            - "5432:5432"